---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "airflow-monitor.fullname" . }}-vault-cert-staging
  labels:
    {{- include "airflow-monitor.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ include "airflow-monitor.fullname" . }}-vault-staging
    kind: SecretStore
  target:
    name: {{ include "airflow-monitor.fullname" . }}-cert-staging
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.vault.staging.certPath }}
        property: certificate
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.vault.staging.certPath }}
        property: private_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "airflow-monitor.fullname" . }}-vault-cert-prod
  labels:
    {{- include "airflow-monitor.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ include "airflow-monitor.fullname" . }}-vault-prod
    kind: SecretStore
  target:
    name: {{ include "airflow-monitor.fullname" . }}-cert-prod
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.vault.prod.certPath }}
        property: certificate
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.vault.prod.certPath }}
        property: private_key 