---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "airflow-monitor.fullname" . }}-vault-staging
  labels:
    {{- include "airflow-monitor.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.staging.address }}
      path: secret
      version: v2
      auth:
        cert:
          clientCert:
            key: tls.crt
            name: {{ include "airflow-monitor.fullname" . }}-cert-staging
          clientKey:
            key: tls.key
            name: {{ include "airflow-monitor.fullname" . }}-cert-staging
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "airflow-monitor.fullname" . }}-vault-prod
  labels:
    {{- include "airflow-monitor.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.prod.address }}
      path: secret
      version: v2
      auth:
        cert:
          clientCert:
            key: tls.crt
            name: {{ include "airflow-monitor.fullname" . }}-cert-prod
          clientKey:
            key: tls.key
            name: {{ include "airflow-monitor.fullname" . }}-cert-prod 